### ISSUE TITLE
CubeSatSim Lite

### ISSUE THREAD

**Issue by roypyp** [alanbjohnston/CubeSatSim#272]
I have a few questions about CubeSatSim Lite.

First, I would like to know if you have an example of telemetry or an explanation of the telemetry list of the CubeSatSim Lite.
Second, can we simulate an attack on that model?

I appreciate any help you can provide,
Roy.

**Comment by alanbjohnston** [comment]
Hi Roy,

These type of questions are best discussed Discussions https://github.com/alanbjohnston/CubeSatSim/discussions so let's have followup discussions there.

First, note that the CubeSatSim Lite is the same software as the full CubeSatSim.  The difference is that the Lite board doesn't have any sensors, just a Low Pass Filter and some buttons and LEDs to change modes.

The CubeSatSim software mimics the telemetry format of the Fox-1 series of CubeSats built by AMSAT.  The format and details of the telemetry are published in various places including the AMSAT Journal and the AMSAT Space Symposium Proceedings.

As for simulating an attack, I don't quite know what you mean. Currently, the CubeSatSim just transmits a telemetry beacon.  There is no uplink command and control over the radio.  Is that the attack vector you are thinking of?  In the future, we may add a simple command and control ability to turn the beacon on and off.

If I am missing the point or you need more information, feel free to post in Discussions so we can have more back and forth and others can also weigh in.

Thanks,
Alan

**Comment by alanbjohnston** [comment]
Discussion should move to https://github.com/alanbjohnston/CubeSatSim/discussions
