### ISSUE TITLE
Qwiic mounting direction of solar board

### ISSUE THREAD

**Issue by kei-Shima** [alanbjohnston/CubeSatSim#301]
Thank you for developing Cubesatsim.

We are working on v1.3.2. There is a picture of the Qwiic installed on the solar board description page, I think the Qwiic connection direction is reversed.
If we check the silk print on the board, there is no problem. However, I think there are some people who will make the board based on the photo, so I would appreciate it if you could replace the photo with the one shown.

[https://github.com/alanbjohnston/CubeSatSim/wiki/v1.3.2-6.-Solar-Board](https://github.com/alanbjohnston/CubeSatSim/wiki/v1.3.2-6.-Solar-Board)
![image](https://github.com/alanbjohnston/CubeSatSim/assets/26500437/a713b870-cdd4-4ce4-8255-a4e562e82fac)

**Comment by alanbjohnston** [comment]
Good catch!  I have fixed the images in four places where it is shown upside down!  Thanks!
