### ISSUE TITLE
Build of Materials OctoPart Mismatch 1x8 Header

### ISSUE THREAD

**Issue by FightFooters** [alanbjohnston/CubeSatSim#315]
Hi Alan,

Just wanted to bring your attention that the 1x8 header in the Stem Payload Board has a mismatched part number in Octopart. This is for the new beta v1.3.2 CubeSatSim.

The Google Sheets has it as the part as PPTC081LFBN-RC, however Octopart mismatches it to PPTC061LFBN-RC, which is a 1x6 header. 

73, 
Ron K5SUS

**Comment by alanbjohnston** [comment]
Thanks, Ron, I fixed it.

It is a database issue in Octopart.  The Matches column showed multiple choices, and one of the choices was for the 1x8 and the other was for a 1x6. Unfortunately, the one chosen by default was the incorrect 1x6 part.  This has happened a few times in the past 12 months or so.  It is annoying, but I still think Octopart is worth using, despite these issues that pop up.  

Hopefully you found this issue when you were reviewing the Shopping Cart, and not after you received the shipment.

73,
Alan
KU2Y
