### ISSUE TITLE
No CubeSatSim Band Pass Filter detected

### ISSUE THREAD

**Issue by Equis-X** [alanbjohnston/CubeSatSim#320]
I've just built the cubesatsim v1.2 and for some reason I'm getting the following error message when running CubeSatSim/cubesatsim:
`...
No CubeSatSim Band Pass Filter detected.  No transmissions after the CW ID.
 See http://cubesatsim.org/wiki for info about building a CubeSatSim
...
`

And I'm sure I soldered the low pass filter to it.
![IMG_3345](https://github.com/alanbjohnston/CubeSatSim/assets/43837752/b940a109-603c-4ecd-a20a-7e1a1f4f2352)
What do I need to do for it to be detected by the software?

**Comment by alanbjohnston** [comment]
Hi, please post this question on the Discussion forum and I will provide assistance.

https://github.com/alanbjohnston/CubeSatSim/discussions

Thanks,
Alan
